### PR TITLE
Fix "modification requires exclusive access" crash when building with…

### LINKED ISSUE #72: Simultaneous access to memory due to KVO in Xcode 9
###  What did you do?

Migrated the project to Swift 4
Ran the demo project in Xcode 9

### What did you expect to happen?

No console warnings

### What happened instead?

A warning in the console about simultaneous access to memory.
```
Simultaneous accesses to 0x7faca830da08, but modification requires exclusive access.
Previous access (a modification) started at PullToRefresh`PullToRefresh.addScrollViewObserving() + 377 (0x1013a4919).
Current access (a modification) started at:
0    libswiftCore.dylib                 0x00000001049947a0 swift_beginAccess + 505
1    PullToRefresh                      0x00000001013a0e70 PullToRefresh.contentOffsetKVOContext.materializeForSet + 38
2    PullToRefresh                      0x00000001013a1370 PullToRefresh.observeValue(forKeyPath:of:change:context:) + 185
3    PullToRefresh                      0x00000001013a4500 @objc PullToRefresh.observeValue(forKeyPath:of:change:context:) + 648
4    Foundation                         0x000000010140ccfd NSKeyValueNotifyObserver + 349
5    Foundation                         0x00000001013ed33f -[NSObject(NSKeyValueObserverRegistration) _addObserver:forProperty:options:context:] + 255
6    Foundation                         0x00000001013ec2a5 -[NSObject(NSKeyValueObserverRegistration) addObserver:forKeyPath:options:context:] + 103
7    PullToRefresh                      0x00000001013a47a0 PullToRefresh.addScrollViewObserving() + 473
8    PullToRefresh                      0x000000010139ed10 PullToRefresh.scrollView.didset + 191
9    PullToRefresh                      0x000000010139ebc0 PullToRefresh.scrollView.setter + 240
10   PullToRefresh                      0x000000010139c790 UIScrollView.addPullToRefresh(_:action:) + 125
11   PullToRefresh                      0x000000010139cec0 @objc UIScrollView.addPullToRefresh(_:action:) + 135
12   PullToRefreshDemo                  0x00000001010a3940 ViewController.setupPullToRefresh() + 485
13   PullToRefreshDemo                  0x00000001010a38a0 ViewController.viewDidLoad() + 81
14   PullToRefreshDemo                  0x00000001010a3d20 @objc ViewController.viewDidLoad() + 36
15   UIKit                              0x00000001026ac87e -[UIViewController loadViewIfRequired] + 1235
16   UIKit                              0x00000001026f4498 -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 68
17   UIKit                              0x00000001026f477f -[UINavigationController _startTransition:fromViewController:toViewController:] + 153
18   UIKit                              0x00000001026f55e6 -[UINavigationController _startDeferredTransitionIfNeeded:] + 841
19   UIKit                              0x00000001026f6b1d -[UINavigationController __viewWillLayoutSubviews] + 115
20   UIKit                              0x000000010294d1c7 -[UILayoutContainerView layoutSubviews] + 231
21   UIKit                              0x00000001025dd01e -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1331
22   QuartzCore                         0x0000000109a55421 -[CALayer layoutSublayers] + 153
23   QuartzCore                         0x0000000109a59418 CA::Layer::layout_if_needed(CA::Transaction*) + 401
24   QuartzCore                         0x00000001099e2060 CA::Context::commit_transaction(CA::Transaction*) + 365
25   QuartzCore                         0x0000000109a0d8f0 CA::Transaction::commit() + 500
26   UIKit                              0x000000010252a679 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 141
27   CoreFoundation                     0x0000000102037200 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
28   CoreFoundation                     0x000000010201b970 __CFRunLoopDoBlocks + 203
29   CoreFoundation                     0x000000010201ad00 __CFRunLoopRun + 1300
30   CoreFoundation                     0x000000010201a8f0 CFRunLoopRunSpecific + 409
31   GraphicsServices                   0x000000010931a988 GSEventRunModal + 62
32   UIKit                              0x000000010250ec91 UIApplicationMain + 159
33   PullToRefreshDemo                  0x00000001010a5c40 main + 55
34   libdyld.dylib                      0x0000000106bf1d80 start + 1
```

### Your Environment

- Version of the component: 2.0.2
- Swift version: 4
- iOS version: 11
- Device: iPhone 8
- Xcode version: 9 GM

### Project that demonstrates the bug

Run the demo project with Xcode 9

### PR DESCRIPTION
**Pull request by nolanw**
… iOS 11 SDK

Shout out to http://michael-brown.net/2017/swift-and-kvo-context-variables/

Fixes #72.

This fix is probably preferable to full-on Swift 4 migration until https://bugs.swift.org/browse/SR-5752 is dealt with.

(Also kinda feels like we're past due for a version bump?)

### CODE REVIEW

**Comment by JMStack** [comment]
accept this PR please, we really need this changes

**Comment by nolanw** [comment]
@JMStack can you point to the PR branch while you wait for upstream to pull in the changes? e.g.
```ruby
pod 'PullToRefresher', :git => 'https://github.com/MindSea/PullToRefresh', :branch => 'fix-simultaneous-access'
```
if you use CocoaPods.

**Comment by romainbiard** [comment]
up ?

**Comment by srj0x0** [comment]
@nolanw , thanks you very much! It's really good solution.

**Pull request merged**
