### PR TITLE
Swift4

### PR DESCRIPTION
**Pull request by arlo-egg**
* Migrates the demo and framework to Swift 4
* Uses optimal build settings
* Fixes issue #72 by using the new `#keyPath` and block based KVO syntax 

#72 was caused by KVO. I found a reference to the new memory access checker being too conservative with KVO contexts here: https://bugs.swift.org/browse/SR-5439 and it looks like it was intended to be fixed by Swift 4 here: https://github.com/apple/swift/pull/11150. However the issue is still present in Xcode 9 GM. Possibly because there were multiple observers with the same context but it looks to me like the syntax is used as intended. 

I tried using multiple contexts; one for each keypath being observed but this did not work. I tried using `.initial` instead of `.new` as recommended but this did not work.

### CODE REVIEW

**Comment by nolanw** [comment]
Just FYI, I'm seeing crashes about a PullToRefresh getting deallocated with KVO observers still attached. I tried inserting a `observers.forEach { $0.invalidate() }` after verifying that `deinit` was being called, still crashing.

Looks a lot like this bug https://bugs.swift.org/browse/SR-5752

**Comment by arlo-egg** [comment]
@nolanw I haven't seen those crashes in production but Xcode certainly is throwing an exception during development on iOS 10. How frustrating that both styles of KVO seem to be broken at the same time.

**Comment by nolanw** [comment]
@arlo-egg I think we can keep using the old style (see #75), so that's something. But yeah it's a bummer, the new style looks pretty cool.

**Comment by srj0x0** [comment]
@arlo-egg , thank you! Problem was solved at MR #75. Check it out and let us know if anything isn’t ok.

**Pull request closed without merging**
